//! omaboot as an application of its own.
//!
//! Inside `omarchy-shell` the window is one of the shell's, and a dock or a
//! task bar shows it under the shell's app id and icon: Quickshell gives
//! every window of a process the same id. The same QML run by a Quickshell
//! instance of its own, with `//@ pragma AppId omaboot`, is a window called
//! `omaboot`, and a desktop entry with that name gives it omaboot's icon.
//!
//! The application directory is generated, never edited: `shell.qml` opens
//! the window and quits when it closes, `Commons` and `Ui` link to the
//! shell's own modules so the window is themed exactly as the plugin is, and
//! the plugin's files are linked in beside them.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::error::{Error, Result};
use crate::exec::which;
use crate::paths::Layout;

/// The app id the window carries, the name of the desktop entry and of the icon.
pub const APP_ID: &str = "omaboot";

/// The icon at the sizes an icon theme wants, straight from `brand/`.
const ICONS: &[(u32, &[u8])] = &[
    (16, include_bytes!("../../../brand/icon-16.png")),
    (32, include_bytes!("../../../brand/icon-32.png")),
    (48, include_bytes!("../../../brand/icon-48.png")),
    (64, include_bytes!("../../../brand/icon-64.png")),
    (128, include_bytes!("../../../brand/icon-128.png")),
    (256, include_bytes!("../../../brand/icon-256.png")),
    (512, include_bytes!("../../../brand/icon-512.png")),
];

const SHELL_QML: &str = r#"//@ pragma AppId omaboot
// Generated by `omaboot app`; edit plugin/Omaboot.qml instead.
import QtQuick
import Quickshell
import Quickshell.Io
import qs.Commons

ShellRoot {
  Omaboot {
    id: app
    Component.onCompleted: open("{}")
    // The plugin asks the shell to hide it; here there is no shell, so a
    // closed window is the end of the program.
    onOpenedChanged: if (!opened) Qt.quit()
  }

  // The shell hears of a theme switch over IPC from omarchy-theme-set. This
  // instance is not the shell, so every two seconds it reads colors.toml
  // through the current-theme link again and, when the text differs from
  // what it applied last, applies the pair of files the way the shell's
  // applyTheme does. Reading through the link catches the link being
  // repointed as well as the file being edited in place.
  readonly property string themeLink: Quickshell.env("HOME") + "/.local/state/omarchy/current/theme"

  FileView {
    id: colorsFile
    property string applied: ""
    path: themeLink + "/colors.toml"
    printErrors: false
    onLoaded: {
      var now = text()
      if (now === applied) return
      applied = now
      Color.loadColors(now)
      shellFile.reload()
      Style.scheduleRefresh()
    }
  }
  FileView {
    id: shellFile
    path: themeLink + "/shell.toml"
    printErrors: false
    onLoaded: Color.loadShell(text())
    onLoadFailed: Color.loadShell("")
  }
  Timer {
    interval: 2000
    running: true
    repeat: true
    onTriggered: colorsFile.reload()
  }
}
"#;

/// Where the generated application lives.
pub fn app_dir(layout: &Layout) -> PathBuf {
    layout.config_dir().join("app")
}

/// `~/.local/share`, where desktop entries and icons go.
pub fn data_base(layout: &Layout) -> PathBuf {
    std::env::var_os("XDG_DATA_HOME")
        .map(PathBuf::from)
        .filter(|p| p.is_absolute())
        .or_else(|| std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".local/share")))
        .unwrap_or_else(|| layout.config_base().join("../.local/share"))
}

pub fn desktop_entry(layout: &Layout) -> PathBuf {
    data_base(layout)
        .join("applications")
        .join(format!("{APP_ID}.desktop"))
}

fn icon_path(layout: &Layout, size: u32) -> PathBuf {
    data_base(layout)
        .join("icons/hicolor")
        .join(format!("{size}x{size}"))
        .join("apps")
        .join(format!("{APP_ID}.png"))
}

/// The shell's QML tree, whose `Commons` and `Ui` the window is built on.
pub fn shell_dir() -> Result<PathBuf> {
    let mut candidates = Vec::new();
    if let Some(path) = std::env::var_os("OMARCHY_PATH") {
        candidates.push(PathBuf::from(path).join("shell"));
    }
    if let Some(home) = std::env::var_os("HOME") {
        candidates.push(PathBuf::from(home).join(".local/share/omarchy/shell"));
    }
    candidates.push(PathBuf::from("/usr/share/omarchy/shell"));
    candidates
        .into_iter()
        .find(|dir| dir.join("Commons/qmldir").is_file() && dir.join("Ui/qmldir").is_file())
        .ok_or_else(|| Error::Environment {
            what: "the Omarchy shell's QML (shell/Commons, shell/Ui) was not found".to_string(),
            suggestion: "set OMARCHY_PATH to the Omarchy tree; the window is built on the shell's own widgets".to_string(),
        })
}

/// Generate the application directory: the entry point, links to the
/// shell's modules, links to the plugin's files. Idempotent, and cheap
/// enough to run before every launch, so it can never be stale.
pub fn prepare(layout: &Layout, plugin: &Path, shell: &Path, dry_run: bool) -> Result<PathBuf> {
    let dir = app_dir(layout);
    if !dry_run {
        fs::create_dir_all(&dir).map_err(|error| Error::write(dir.clone(), error))?;
        fs::write(dir.join("shell.qml"), SHELL_QML)
            .map_err(|error| Error::write(dir.join("shell.qml"), error))?;
    }
    for module in ["Commons", "Ui"] {
        link(&shell.join(module), &dir.join(module), dry_run)?;
    }
    // Every QML and JavaScript file of the plugin, by name, so that the
    // plugin's relative imports resolve here as they do in the shell.
    let mut linked = 0;
    for entry in fs::read_dir(plugin).map_err(|error| Error::read(plugin.to_path_buf(), error))? {
        let entry = entry.map_err(|error| Error::read(plugin.to_path_buf(), error))?;
        let path = entry.path();
        let is_source = path
            .extension()
            .map(|ext| ext == "qml" || ext == "js")
            .unwrap_or(false);
        if !is_source {
            continue;
        }
        link(&path, &dir.join(entry.file_name()), dry_run)?;
        linked += 1;
    }
    if linked == 0 {
        return Err(Error::Environment {
            what: format!("no QML in {}", plugin.display()),
            suggestion: "point OMABOOT_PLUGIN_DIR at the plugin directory".to_string(),
        });
    }
    Ok(dir)
}

/// The desktop entry and the icons, so launchers and docks know omaboot.
pub fn install(layout: &Layout, plugin: &Path, dry_run: bool, out: &mut dyn Write) -> Result<()> {
    let shell = shell_dir()?;
    let dir = prepare(layout, plugin, &shell, dry_run)?;
    let verb = if dry_run { "would write" } else { "wrote" };
    writeln!(
        out,
        "{verb}      {} (shell.qml, Commons, Ui, the plugin)",
        dir.display()
    )
    .ok();

    for (size, bytes) in ICONS {
        let path = icon_path(layout, *size);
        write_file(&path, bytes, dry_run)?;
    }
    writeln!(
        out,
        "{verb}      {}/<size>/apps/{APP_ID}.png ({} sizes)",
        data_base(layout).join("icons/hicolor").display(),
        ICONS.len()
    )
    .ok();

    let entry = desktop_entry(layout);
    write_file(&entry, desktop_entry_text().as_bytes(), dry_run)?;
    writeln!(out, "{verb}      {}", entry.display()).ok();

    if !dry_run && !layout.is_prefixed() {
        // Not every launcher watches the directory; a refresh does no harm.
        if let Some(tool) = which(layout, "update-desktop-database") {
            let _ = Command::new(tool)
                .arg(entry.parent().expect("entry has a parent"))
                .output();
        }
    }
    writeln!(
        out,
        "\nlaunch it as \"omaboot\" from the app launcher, or with `omaboot app`"
    )
    .ok();
    Ok(())
}

pub fn uninstall(layout: &Layout, dry_run: bool, out: &mut dyn Write) -> Result<()> {
    let verb = if dry_run { "would remove" } else { "removed" };
    let mut paths = vec![desktop_entry(layout)];
    paths.extend(ICONS.iter().map(|(size, _)| icon_path(layout, *size)));
    for path in paths {
        if path.exists() {
            if !dry_run {
                fs::remove_file(&path).map_err(|error| Error::write(path.clone(), error))?;
            }
            writeln!(out, "{verb}    {}", path.display()).ok();
        }
    }
    let dir = app_dir(layout);
    if dir.is_dir() {
        if !dry_run {
            fs::remove_dir_all(&dir).map_err(|error| Error::write(dir.clone(), error))?;
        }
        writeln!(out, "{verb}    {}", dir.display()).ok();
    }
    Ok(())
}

/// Run the window in a Quickshell instance of its own, in the foreground,
/// until it is closed.
pub fn run(layout: &Layout, plugin: &Path, out: &mut dyn Write) -> Result<()> {
    let shell = shell_dir()?;
    let dir = prepare(layout, plugin, &shell, false)?;
    let quickshell = ["qs", "quickshell"]
        .into_iter()
        .find_map(|name| which(layout, name))
        .ok_or_else(|| Error::Environment {
            what: "quickshell (qs) is not on PATH".to_string(),
            suggestion: "Omarchy ships it; install the quickshell package".to_string(),
        })?;
    if layout.is_prefixed() {
        writeln!(
            out,
            "would run  {} -p {}",
            quickshell.display(),
            dir.display()
        )
        .ok();
        return Ok(());
    }
    let status = Command::new(&quickshell)
        .arg("-p")
        .arg(&dir)
        .status()
        .map_err(|error| Error::Environment {
            what: format!("{} could not be started: {error}", quickshell.display()),
            suggestion: "run it by hand to see why".to_string(),
        })?;
    if !status.success() {
        return Err(Error::Environment {
            what: format!("quickshell exited with {status}"),
            suggestion: "its output above says why; `omaboot app install` rewrites the application directory".to_string(),
        });
    }
    Ok(())
}

fn desktop_entry_text() -> String {
    format!(
        "[Desktop Entry]\n\
Type=Application\n\
Name=omaboot\n\
Comment=Design the boot, login and shutdown screens\n\
Exec=omaboot app\n\
Icon={APP_ID}\n\
Terminal=false\n\
Categories=Settings;DesktopSettings;\n\
Keywords=plymouth;sddm;boot;login;theme;\n\
StartupWMClass={APP_ID}\n"
    )
}

fn write_file(path: &Path, bytes: &[u8], dry_run: bool) -> Result<()> {
    if dry_run {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| Error::write(parent.to_path_buf(), error))?;
    }
    fs::write(path, bytes).map_err(|error| Error::write(path.to_path_buf(), error))
}

/// Make `link` point at `target`, replacing a previous link and refusing to
/// replace anything that is not one.
fn link(target: &Path, link: &Path, dry_run: bool) -> Result<()> {
    if link.exists() && !link.is_symlink() {
        return Err(Error::Environment {
            what: format!("{} exists and is not a link", link.display()),
            suggestion: "move it out of the way first".to_string(),
        });
    }
    if dry_run {
        return Ok(());
    }
    if let Some(parent) = link.parent() {
        fs::create_dir_all(parent).map_err(|error| Error::write(parent.to_path_buf(), error))?;
    }
    if link.is_symlink() {
        fs::remove_file(link).map_err(|error| Error::write(link.to_path_buf(), error))?;
    }
    std::os::unix::fs::symlink(target, link)
        .map_err(|error| Error::write(link.to_path_buf(), error))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn world() -> (tempfile::TempDir, Layout, PathBuf, PathBuf) {
        let tmp = tempfile::tempdir().unwrap();
        let layout = Layout::with_dirs(
            Some(tmp.path().join("prefix")),
            tmp.path().join("config/omaboot"),
            tmp.path().join("state/omaboot"),
        );
        let shell = tmp.path().join("omarchy/shell");
        for module in ["Commons", "Ui"] {
            fs::create_dir_all(shell.join(module)).unwrap();
            fs::write(
                shell.join(module).join("qmldir"),
                format!("module qs.{module}\n"),
            )
            .unwrap();
        }
        let plugin = tmp.path().join("plugin");
        fs::create_dir_all(&plugin).unwrap();
        fs::write(plugin.join("Omaboot.qml"), "Item {}\n").unwrap();
        fs::write(plugin.join("icons.js"), "var x = 1\n").unwrap();
        fs::write(plugin.join("manifest.json"), "{}\n").unwrap();
        (tmp, layout, shell, plugin)
    }

    #[test]
    fn the_application_directory_is_the_plugin_on_the_shells_modules() {
        let (_tmp, layout, shell, plugin) = world();
        let dir = prepare(&layout, &plugin, &shell, false).unwrap();
        let entry = fs::read_to_string(dir.join("shell.qml")).unwrap();
        assert!(entry.starts_with("//@ pragma AppId omaboot"), "{entry}");
        assert!(
            entry.contains("Qt.quit()"),
            "closing the window ends the program"
        );
        assert_eq!(
            fs::read_link(dir.join("Commons")).unwrap(),
            shell.join("Commons")
        );
        assert_eq!(fs::read_link(dir.join("Ui")).unwrap(), shell.join("Ui"));
        assert_eq!(
            fs::read_link(dir.join("Omaboot.qml")).unwrap(),
            plugin.join("Omaboot.qml")
        );
        assert_eq!(
            fs::read_link(dir.join("icons.js")).unwrap(),
            plugin.join("icons.js")
        );
        assert!(
            !dir.join("manifest.json").exists(),
            "only sources are linked"
        );
        // Running it again is fine.
        prepare(&layout, &plugin, &shell, false).unwrap();
    }

    #[test]
    fn the_desktop_entry_names_the_app_id_and_the_icon() {
        let text = desktop_entry_text();
        assert!(text.contains("Exec=omaboot app\n"));
        assert!(text.contains("Icon=omaboot\n"));
        assert!(text.contains("StartupWMClass=omaboot\n"));
    }

    #[test]
    fn icons_and_entry_land_under_the_data_directory_and_leave_with_uninstall() {
        let (tmp, layout, shell, plugin) = world();
        // The data directory follows XDG_DATA_HOME; this test owns its own.
        let data = tmp.path().join("data");
        let icon = data
            .join("icons/hicolor/64x64/apps")
            .join(format!("{APP_ID}.png"));
        let entry = data.join("applications").join(format!("{APP_ID}.desktop"));
        // write_file and the paths are exercised directly, since the
        // environment is process-wide and not this test's to change.
        let dir = prepare(&layout, &plugin, &shell, false).unwrap();
        for (size, bytes) in ICONS {
            let path = data
                .join("icons/hicolor")
                .join(format!("{size}x{size}"))
                .join("apps")
                .join(format!("{APP_ID}.png"));
            write_file(&path, bytes, false).unwrap();
        }
        write_file(&entry, desktop_entry_text().as_bytes(), false).unwrap();
        assert!(icon.is_file());
        assert!(fs::read(&icon).unwrap().starts_with(b"\x89PNG"));
        assert!(entry.is_file());
        assert!(dir.join("shell.qml").is_file());
        let _ = uninstall(&layout, false, &mut Vec::new());
        assert!(!dir.exists(), "the generated directory is gone");
    }
}
